version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3307
      DB_DATABASE: sistema-rh
      DB_USERNAME: root
      DB_PASSWORD: 123456
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: sistema-rh
      # MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
volumes:
  db_data:
